name: 'industrial_sustainability'
version: '1.0.0'

profile: 'industrial_sustainability'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  industrial_sustainability:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table