industrial_sustainability:

  target: dev

  outputs:

    dev:

      type: mysql
      server: "{{ env_var('MYSQL_HOST', 'host.docker.internal') }}"
      port: "{{ env_var('MYSQL_PORT', '3306') | int }}"
      username: "{{ env_var('MYSQL_USER', 'root') }}"
      password: "{{ env_var('MYSQL_PASSWORD') }}"
      schema: "{{ env_var('MYSQL_DATABASE', 'helios_industrial_group') }}"
      database: "{{ env_var('MYSQL_DATABASE', 'helios_industrial_group') }}"
      threads: 1